name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: deploy-session-mendako-bocchi-chang
          aws-region: ${{ env.AWS_REGION }}
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Download assets
        run:
          aws s3 sync s3://${{ secrets.AWS_RESOUCE_BUCKET_NAME }}/audio ./public/audio
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to S3
        run:
          aws s3 sync --delete ./dist s3://${{ secrets.AWS_BUCKET_NAME }}/games/mendako-bocchi-chang
      - name: Evict CloudFront cache
        run:
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/games/mendako-bocchi-chang/*"
